name: foodie_screen
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  simple_search_dropdown: ^5.2.0
  flutter_lints: ^4.0.0
  social_login_buttons: ^1.0.7
  firebase_core: ^3.8.1
  provider: ^6.1.2
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.0
  shared_preferences: ^2.3.4
  intl: ^0.20.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  http: ^1.2.2
  


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF_black_Italic_title.otf
          weight: 900
          style: italic
        - asset: assets/fonts/SF_heavy_italic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/SF_bold.otf
          weight: 700
        - asset: assets/fonts/SF_light_italic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/SF_medium.otf
          weight: 500
        - asset: assets/fonts/SF_regular.otf
          weight: 400
        - asset: assets/fonts/SF_semibold_italic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/SFPRODISPLAYTHINITALIC.OTF
          weight: 100
          style: italic
        - asset: assets/fonts/SF_ultra_light_italic.otf
          weight: 200
          style: italic


